name: Release

on: workflow_dispatch  # Run workflow manually

jobs:
  release:
    name: Release on Sonatype OSS
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_GH_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup Java 11 and Apache Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        run: mvn -B clean release:clean release:prepare release:perform
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
